project:
  type: book

book:
  title: "<%= title %>"
  author: "Jane Doe"
  date: "<%= new Date().toLocaleDateString() %>"
  contents:
    - index<%= ext %>
    - intro<%= ext %>
    - summary<%= ext %>
  references: references<%= ext %>

bibliography: references.bib

format:
  html:
    theme: cosmo
  epub: default
  pdf: default
