project:
  type: book

contents:
  - text: "Preface"
    file: index<%= ext %>
  - intro<%= ext %>
  - summary<%= ext %>
  - references<%= ext %>

bibliography: references.bib

format:
  html:
    theme: [cosmo, assets/html-theme.scss]
  epub:
    css: assets/epub-styles.css
    cover-image: assets/epub-cover.png
  pdf:
    include-in-header: assets/pdf-preamble.tex
