project:
  type: book

book:
  contents:
    - index<%= ext %>
    - intro<%= ext %>
    - summary<%= ext %>
  references: references<%= ext %>

bibliography: references.bib

format:
  html:
    theme: [cosmo, assets/html-theme.scss]
  epub:
    css: assets/epub-styles.css
    epub-cover-image: assets/epub-cover.png
  pdf:
    include-in-header: assets/pdf-preamble.tex
