project:
  type: site
  output-dir: <%= outputDir %>

site-title: "<%= title %>"

nav-top:
  type: dark
  background: primary
  left:
    - href: index<%= ext %>
      text: Home
    - about<%= ext %>

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
