project:
  title: "<%= title %>"
  type: website
  output-dir: <%= outputDir %>

nav-top:
  type: dark
  background: primary
  left:
    - href: index<%= ext %>
      text: Home
    - href: about<%= ext %>

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
