name: 'Configure Computation Environment'
description: 'Configures a machine with computation dependencies.'
inputs:
  r-version:
    description: 'The R version'
    required: false
    default: '4.02'

  python-version:  
    description: 'The python version'
    required: false
    default: '3.x'


runs:
  using: "composite"
  steps: 

      - name: Set up R 
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ inputs.r-version }}

      - name: Cache packages
        uses: actions/cache@v1
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python-version }}
      
      - name: Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter