- name: project
  schema:
    object:
      properties:
        type:
          enum: [website, book, site]
          completions: [website, book]
          description: "Project type"
        render:
          arrayOf: path
          description: "Files to render (defaults to all files)"
        execute-dir:
          enum: [file, project]
          description:
            short: "Working directory for computations"
            long: |
              Working directory for computations: `file` uses the directory of the
              currently executing file, `project` uses the root project directory.
        output-dir:
          path:
            description: "Output directory"
        lib-dir:
          path:
            description: "HTML library (JS/CSS/etc.) directory"
        resources:
          arrayOf:
            schama: path
            description: "Additional file resources to be copied to output directory"

- name: website
  schema:
    ref: base-website

- name: book
  schema:
    object:
      super:
        resolveRef: base-website
      properties:
        output-file:
          path:
            description: "etc"
