- id: yaml-schema/base
  object:
    properties:
      id: string
      completions:
        anyOf:
          - arrayOf: string
          - object:
              additionalProperties: string

      additionalCompletions:
        anyOf:
          - arrayOf: string
          - object:
              additionalProperties: string

- id: yaml-schema/object
  object:
    super:
      resolveRef: yaml-schema/base
    properties:
      closed:
        enum: [true] # only allow the boolean 'true' value (denoting as 'true' would instead allow anything)
      required:
        anyOf:
          - enum:
              - all
          - arrayOf: string
      super:
        ref: yaml-schema/object
        description: be a yaml object schema
      hidden: boolean
      additionalProperties:
        ref: yaml-schema/schema
        description: be a yaml yaml schema
      properties:
        object:
          additionalProperties:
            ref: yaml-schema/schema
            description: be a yaml yaml schema

- id: yaml-schema/enum
  object:
    super:
      resolveRef: yaml-schema/base
    properties:
      enum:
        anyOf:
          - arrayOf: string
          - object:
              super:
                resolveRef: yaml-schema/base
              properties:
                values:
                  arrayOf: string

- id: yaml-schema/ref
  object:
    properties:
      ref: string
      description: string
    closed: true
    required: ref

- id: yaml-schema/resolveRef
  object:
    properties:
      resolveRef: string
    closed: true
    required: resolveRef

- id: yaml-schema/maybe-array-of
  object:
    super:
      resolveRef: yaml-schema/base
    properties:
      maybeArrayOf:
        ref: yaml-schema/schema
        description: be a yaml yaml schema
    closed: true
    required: all

- id: yaml-schema/array-of
  object:
    super:
      resolveRef: yaml-schema/base
    properties:
      arrayOf:
        anyOf:
          - arrayOf:
              ref: yaml-schema/schema
              description: be a yaml yaml schema
          - object:
              super:
                resolveRef: yaml-schema/base
              properties:
                schema:
                  arrayOf:
                    ref: yaml-schema/schema
                    description: be a yaml yaml schema
    required: [arrayOf]

- id: yaml-schema/enum
  anyOf:
    schemas:
      - arrayOf: string
      - object:
          super:
            resolveRef: yaml-schema/base
          properties:
            values:
              arrayOf: string

- id: yaml-schema/any-of
  object:
    super:
      resolveRef: yaml-schema/base
    properties:
      anyOf:
        anyOf:
          - arrayOf:
              ref: yaml-schema/schema
              description: be a yaml yaml schema
          - object:
              super:
                resolveRef: yaml-schema/base
              properties:
                schemas:
                  arrayOf:
                    ref: yaml-schema/schema
                    description: be a yaml yaml schema

- id: yaml-schema/schema
  anyOf:
    schemas:
      - enum:
          - object
          - string
          - number
          - path
          - boolean

      - resolveRef: yaml-schema/ref
      - resolveRef: yaml-schema/maybe-array-of
      - resolveRef: yaml-schema/array-of
      - resolveRef: yaml-schema/any-of
      - resolveRef: yaml-schema/enum
      - resolveRef: yaml-schema/object
