name: 'Configure Apple Certificate'
description: 'Configures a P12 certificate into the keychain for signing'
inputs:
  certificate-value:
    description: 'A base64 encoded string representing the p12 value of the certificate.'
    required: true
    default: ''

  certificate-password:  
    description: 'The password for the certificate'
    required: true
    default: ''

  keychain:
    description: 'The name of the keychain to install the certificate into'
    required: true
    default: ''

  certificate-file:
    description: 'Intermediary name for p12 file'
    required: false
    default: 'certificate.p12'


runs:
  steps: 
     - name: Add Installer Cert
       if: ${{ matrix.os == 'macos-latest' }}
       run: |
         echo "HELLO WORLD"
        
       shell: bash


