name: "Configure Quarto Dev"
description: "Configures the image for Quarto Development"

runs:
  using: "composite"
  steps:
    - name: Configure Quarto (.sh)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        ./configure.sh
        echo "$HOME/bin" >> $GITHUB_PATH

    - name: Configure Quarto (.ps1)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        ./configure.cmd
        $env:QUARTO_BIN_DEV >> $env:GITHUB_PATH

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3

    - shell: pwsh
      run: $env:PATH -Split ";"

    - name: Basic dev mode sanity check
      shell: pwsh
      run: |
        If ( "$(quarto --version)" -ne "99.9.9") { Exit 1 }
        If ( -not $(quarto --paths | Select-String -Pattern "package[/\\]+dist[/\\]+share") -ne $null ) { Exit 1 }
        If ( -not "$(git status --porcelain)" -ne "" ) { Exit 1 }

    - name: Quarto Check
      working-directory: tests
      shell: pwsh
      run: quarto check
