project:
  type: website

website:
  title: "<%= title %>"
  navbar:
    background: primary
    left:
      - href: index<%= ext %>
        text: Home
      - about<%= ext %>
    right:
      - icon: github
        href: https://www.github.com/
      - icon: twitter
        href: https://www.twitter.com
format:
  html:
    theme: cosmo
    css: styles.css

<% if(editor){ %>editor: <%= editor %><% } %>
