project:
  type: website

website:
  title: "<%= title %>"
  navbar:
    background: primary
    left:
      - href: index<%= ext %>
        text: Home
      - about<%= ext %>

format:
  html:
    theme: united
    css: styles.css

<% if(editor){ %>editor: <%= editor %><% } %>
