name: Daily Release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'  # every day at one am

jobs:
  make-installer-deb:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure
      run: |
        ./configure-linux.sh

    - name: Prepare Distribution
      run: |
        pushd package/src/
        ./quarto-pack prepare-dist --log-level info
        popd

    - name: Make Installer
      run: |
        pushd package/src/
        ./quarto-pack make-installer-deb --log-level info
        popd

  make-installer-win:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure
      run: |
        configure-windows.cmd

    - name: Prepare Distribution
      run: |
        pushd package\src\
        quarto-pack.cmd prepare-dist --log-level info
        popd

    - name: Make Installer
      run: |
        pushd package\src\
        quarto-pack.cmd make-installer-win --log-level info
        popd        

  make-installer-mac:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure
      run: |
        ./configure-macos.sh

    - name: Prepare Distribution
      run: |
        pushd package/src/
        ./quarto-pack prepare-dist --log-level info
        popd

    - name: Make Installer
      run: |
        pushd package/src/
        ./quarto-pack make-installer-mac --log-level info
        popd