name: Run Smoke Tests

on: 
  workflow_dispatch:
  # push:
    # only trigger on branches, not on tags
    # branches: [ main ]

jobs:
  run-smokes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          # checkout full tree
          fetch-depth: 0
          
      
      - name: Configure Quarto
        run: |         
          ./configure-linux.sh
                    
      - name: Install TinyTex
        run: |
          pushd package/dist/bin/
          ./quarto install tinytex
          popd
          
          pwd
          echo $PATH
          
          # export PATH=/home/dave/work:$PATH
          tlmgr dump-tlpdb --local
              
      - name: Smoke Test Commits
        if: github.event.before != ''
        run: |
          for commit in $(git rev-list ${{ github.event.before}}..${{ github.sha}}); do
              git checkout $commit
              pushd tests
              ./run-tests.sh
              popd
          done
          
      - name: Smoke Test Head
        if: github.event.before == ''
        run: |
              pushd tests
              ./run-tests.sh
              popd
        
