name: Run Smoke Tests

on: 
  workflow_dispatch:
  # push:
    # only trigger on branches, not on tags
    # branches: [ main ]
env:
  RENV_PATHS_ROOT: ~/.local/share/renv
  
# Ubuntu: ~/.local/share/renv
# macOS: ~/Library/Application Support/renv
# Windows: %LOCALAPPDATA%/renv 
  
jobs:
  run-smokes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          # checkout full tree
          fetch-depth: 0

      - uses: ./.github/workflows/actions/computation-environment
        with:
          r-version: '4.02'
          python-version: '3.x'

      - uses: ./.github/workflows/actions/quarto-dev
            
      - name: Smoke Test Commits
        if: github.event.before != ''
        run: |
          for commit in $(git rev-list ${{ github.event.before}}..${{ github.sha}}); do
              git checkout $commit
              pushd tests
              ./run-tests.sh
              popd
          done
          
      - name: Smoke Test Head
        if: github.event.before == ''
        run: |
          pushd tests
          ./run-tests.sh
          popd
        
