name: Run Smoke Tests

on: 
  workflow_dispatch:
  # push:
    # only trigger on branches, not on tags
    # branches: [ main ]
env:
  RENV_PATHS_ROOT: ~/.local/share/renv
  
jobs:
  run-smokes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          # checkout full tree
          fetch-depth: 0

      - name: Set up R 
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.0.2' # The R version to download (if necessary) and use.  

      - name: Cache packages
        uses: actions/cache@v1
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter
      
      - name: Configure Quarto
        run: |         
          ./configure-linux.sh
                    
      - name: Install TinyTex
        run: |
          pushd package/dist/bin/
          ./quarto install tinytex
          popd
          export PATH=/home/runner/bin:$PATH
          
          tlmgr dump-tlpdb --local
              
      - name: Smoke Test Commits
        if: github.event.before != ''
        run: |
          for commit in $(git rev-list ${{ github.event.before}}..${{ github.sha}}); do
              git checkout $commit
              pushd tests
              ./run-tests.sh
              popd
          done
          
      - name: Smoke Test Head
        if: github.event.before == ''
        run: |
              pushd tests
              ./run-tests.sh
              popd
        
