# Tests a broad set of Quarto functionality that users are likely to encounter.
# A failure indicates some signficant portion of functionality is likely to be broken.
name: Smoke Tests
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    # only trigger on branches, not on tags
    branches: [main]

jobs:
  run-smokes:
    strategy:
      fail-fast: false
      matrix:
        #os: [ubuntu-latest, windows-latest]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          # checkout full tree
          fetch-depth: 0

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.2.2"

      - name: Install node (for Playwright)
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install node dependencies
        run: yarn
        working-directory: ./tests/integration/playwright
        shell: bash

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./tests/integration/playwright

      - name: Set RENV_PATHS_ROOT
        shell: bash
        run: |
          echo "RENV_PATHS_ROOT=${{ runner.temp }}/renv" >> $GITHUB_ENV

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-1-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-1-renv-

      - name: Restore R packages
        working-directory: tests
        run: |
          if (!requireNamespace('renv', quietly = TRUE)) install.packages('renv')
          renv::restore()
        shell: Rscript {0}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          cache: "pip"
          python-version-file: "./tests/.python-version"

      - name: Restore Python Dependencies
        working-directory: tests
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install wheel 
          python3 -m pip install -r requirements.txt

      - uses: ./.github/workflows/actions/quarto-dev

      - name: Install Tinytex
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          quarto install tinytex

      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Setup Julia
        uses: julia-actions/setup-julia@v1

      - name: Cache Julia Packages
        uses: julia-actions/cache@v1

      - name: Restore Julia Packages
        working-directory: tests
        shell: bash
        run: |
          julia --color=yes --project=. -e "import Pkg; Pkg.instantiate(); Pkg.build(\"IJulia\"); Pkg.precompile()"

      - name: Setup tmate session
        if: runner.os == 'Windows'
        uses: mxschmitt/action-tmate@v3

      - name: Smoke Test Commits
        if: github.event.before != ''
        env:
          # Useful as TinyTeX latest release is checked in run-test.sh
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout ${{ github.sha}}
          pushd tests
          case $RUNNER_OS in
            "Windows")
              pwsh -F ./run-test.ps1
              ;;
            *)
              ./run-tests.sh
              ;;
          esac
          popd
        shell: bash

      - name: Smoke Test Head
        env:
          # Useful as TinyTeX latest release is checked in run-test.sh
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.event.before == ''
        run: |
          quarto render docs/test.qmd --to pdf
          case $RUNNER_OS in
            "Windows")
              pwsh -F ./run-test.ps1
              ;;
            *)
              ./run-tests.sh
              ;;
          esac
        working-directory: tests
        shell: bash
