# Test building the quarto-latexmk command
on:
  push:
    branches: main
  pull_request:
    branches: main
name: Test quarto-latexmk

jobs:
  quarto-latexmk:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest}
          - {os: macOS-latest}
          - {os: ubuntu-latest}

    steps:
      - uses: actions/checkout@v2

      - name: Test ${{ runner.os }}
        if: runner.os == 'Windows'
        run: |
          .\configure-windows.cmd
          cd package/src
          .\quarto-bld.cmd compile-quarto-latexmk --target x86_64-pc-windows-msvc
          .\..\dist\bin\quarto-latexmk\x86_64-pc-windows-msvc\quarto-latexmk.exe --help

      - name: Test ${{ runner.os }}
        if: runner.os == 'macOS'
        run: |
          ./configure-macos.sh
          cd package/src
          ./quarto-bld compile-quarto-latexmk --target x86_64-apple-darwin
          ../dist/bin/quarto-latexmk/x86_64-apple-darwin/quarto-latexmk --help

      - name: Test ${{ runner.os }}
        if: runner.os == 'Linux'
        run: |
          ./configure-linux.sh
          cd package/src
          ./quarto-bld compile-quarto-latexmk --target x86_64-unknown-linux-gnu
          ../dist/bin/quarto-latexmk/x86_64-unknown-linux-gnu/quarto-latexmk --help
