# Tests a broad set of Quarto functionality that users are likely to encounter.
# A failure indicates some signficant portion of functionality is likely to be broken.
name: Smoke Tests
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    # only trigger on branches, not on tags
    branches: [main]
env:
  RENV_PATHS_ROOT: ~/.local/share/renv

# Ubuntu: ~/.local/share/renv
# macOS: ~/Library/Application Support/renv
# Windows: %LOCALAPPDATA%/renv

jobs:
  run-smokes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          # checkout full tree
          fetch-depth: 0

      - uses: ./.github/workflows/actions/quarto-test-deps

      - uses: ./.github/workflows/actions/quarto-dev

      - name: Install Tinytex
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          quarto install tinytex

      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Setup Julia
        uses: julia-actions/setup-julia@v1

      - name: Julia Packages
        run: |
          pushd tests
          julia --project=. -e "import Pkg; Pkg.instantiate(); Pkg.build(\"IJulia\"); Pkg.precompile()"
          popd

      - name: Smoke Test Commits
        if: github.event.before != ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout ${{ github.sha}}
          pushd tests
          ./run-tests.sh
          popd

      - name: Smoke Test Head
        env:
          # Useful as TinyTeX latest release is checked in run-test.sh
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.event.before == ''
        run: |
          pushd tests
          quarto render docs/test.qmd --to pdf
          ./run-tests.sh
          popd
