# Tests whether Quarto can successfully bundle and run the bundled javascript. 
# If this test fails, the release version of Quarto will error when run since 
# bundling has failed.
name: Bundle Time
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    # only trigger on branches, not on tags
    branches: [main]


jobs:
  test-bundle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          # checkout full tree
          fetch-depth: 0

      - name: Set Path
        shell: bash
        run: |
          echo "$HOME/bin" >> $GITHUB_PATH
      
      - name: Configure Quarto
        shell: bash
        run: |
          ./configure-linux.sh

      - name: Test Bundle
        id: test-bundle
        shell: bash
        run: |
          pushd package/src

          bundle_start=$(date +%s.%3N)
          ./quarto-bld prepare-dist
          bundle_end=$(date +%s.%3N)
          bundle_elapsed=$(echo "scale=3; $bundle_end - $bundle_start" | bc)
          echo $(bundle_elapsed)
          
          mv ../../src/quarto.ts ../../src/quarto1.ts 

          q_start=$(date +%s.%3N)
          quarto
          q_end=$(date +%s.%3N)
          q_elapsed=$(echo "scale=3; $q_end - $q_start" | bc)
          echo $(q_elapsed)
          
          echo $(git rev-parse --short '$GITHUB_SHA')

          echo "::set-output name=bundle_time:$(bundle_elapsed)\n"
          echo "::set-output name=q_time:$(q_elapsed)\n"
          echo "::set-output name=commit:$(git rev-parse --short '$GITHUB_SHA')"

      - name: Send Event
        uses: ./.github/workflows/actions/amplitude
        with:
          api_key: ${{ secrets.amplitude_api_key }}
          event: "Bundle"
          success: true
          duration: ${{ steps.test-bundle.outputs.bundle_time }}
          commit: ${{ steps.test-bundle.outputs.commit }}

    

